# This is the configuration file for your production environment.
#
# To improve scalability and reliability it's possible to run Serverpod over a
# cluster of servers. The ids of the servers should be in a consecutive sequence
# from 0 to n-1 where n is the number of servers in your cluster.

# Defines public facing access to the server, in production mode this will be
# the address of your load balancer or cloud front.
public_host: api.example.com
public_port: 443
public_scheme: https

cluster:
  # Configuration for server id 0
  0:
    # Main port to run the server on.
    port: 8080
    # Service port, used for communication between servers in a cluster or for
    # gaining insights from the server while it's running.
    servicePort: 8081
    # Host used to connect to the server.
    address: private-access-0.example.com

  # Configuration for server id 1
  1:
    # Main port to run the server on.
    port: 8080
    # Service port, used for communication between servers in a cluster or for
    # gaining insights from the server while it's running.
    servicePort: 8081
    # Host used to connect to the server.
    address: private-access-1.example.com

# This is the database setup for your servers. You will need to edit this to get
# the server up and running.
database:
  host: database.example.com
  port: 5432
  name: DATABASE_NAME
  user: DATABASE_USER

redis:
  host: localhost
  port: 6379
